# Github Action for running terraform plan on push

name: Terraform Plan

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
    terraform_plan:
        name: Terraform Plan
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
            - name: Terraform fmt
              run: terraform fmt -check
            - name: Terraform Init
              run: terraform init
            - name: Terraform Validate
              run: terraform validate
            - name: Terraform Plan
              run: terraform plan -input=false -no-color
